### PR TITLE
Implement different highland heights

### PR DESCRIPTION
**Pull request by LeMagnesium**
- Implement #47 by spawning highlands at different heights

### CODE REVIEW

**Comment by Ombridride** [comment]
you think a difference of height of 8 is enought ? it seems to me too small, need tests !

**Comment by cornernote** [comment]
Thanks for this!

One small thing, are you able to make it a variable in the config so that the 8 is not hardcoded?

**Comment by LeMagnesium** [comment]
Done.

**Comment by cornernote** [comment]
Thanks!

**Pull request merged**
